#!/bin/sh


Current=$(pwd)

Directory=$1

#Folder2=${/c/Users/jabba/Downloads}



#if its a directory that exist switch to it
if  [ -d $1 ]
then
echo "$1 Directory checks out"
cd $1 
else
echo "$1 isn't a real Directory"
fi



date=$(date '+%Y-%m-%d') 



for FILE in ls *.pdf $1
do 
echo "adding ${date} to ${FILE}"
mv -i -v "$FILE" "${date}$FILE"
done





#switch  back to current directory
cd ${Current}

#rename * ${date}*.pdf *.pdf
